services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      RECOMMENDATION_DATASET: /app/data/raw/sample_movies.csv
      SEMANTIC_MODEL: all-MiniLM-L6-v2
      LLM_MODEL: EleutherAI/gpt-neo-125M

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
