services:
  - type: web
    name: ai-recommendation-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: RECOMMENDATION_DATASET
        value: /app/data/raw/sample_movies.csv
      - key: SEMANTIC_MODEL
        value: all-MiniLM-L6-v2
      - key: LLM_MODEL
        value: EleutherAI/gpt-neo-125M
      - key: LLM_ENABLED
        value: "false"
      - key: SEMANTIC_ENABLED
        value: "false"
      - key: TMDB_ENABLED
        value: "false"
      - key: TMDB_PAGES
        value: "3"
      - key: TMDB_MINIMUM_VOTES
        value: "300"

  - type: web
    name: ai-recommendation-ui
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.streamlit
    dockerContext: .
    envVars:
      - key: API_URL
        value: https://ai-recommendation-api-qa00.onrender.com
